### ISSUE TITLE
Let's play

### ISSUE THREAD

**Issue by michal-hudy** [wookiee-testooja/wez-to-potestuj#8]

**Comment by mh-test** [comment]
![blob](https://cdn.discordapp.com/emojis/580596349284777984.gif?size=64)

**Comment by mh-test** [comment]
![blob](https://cdn.discordapp.com/emojis/580596349284777984.gif?size=64)

**Comment by mh-test** [comment]
![blob](https://cdn.discordapp.com/emojis/614485914961444876.gif?size=64)

**Comment by mh-test** [comment]
![blob](https://cdn.discordapp.com/emojis/543967326219927552.gif?size=64)

**Comment by mh-test** [comment]
![blob](https://cdn.discordapp.com/emojis/580593299857997824.gif?size=64)

**Comment by mh-test** [comment]
![blob](https://cdn.discordapp.com/emojis/635255958930456581.gif?size=64)

**Comment by mh-test** [comment]
@michal-hudy ![blob](https://cdn.discordapp.com/emojis/637851673389432843.gif?size=64)

**Comment by mh-test** [comment]
@michal-hudy ![blob](https://cdn.discordapp.com/emojis/414286078346788864.gif?size=64)

**Comment by mh-test** [comment]
@bszwarc ![blob](https://cdn.discordapp.com/emojis/635256314070695977.gif?size=64)

**Comment by mh-test** [comment]
@michal-hudy ![blob](https://cdn.discordapp.com/emojis/635256384442859530.gif?size=32)

**Comment by mh-test** [comment]
@michal-hudy ![blob](https://cdn.discordapp.com/emojis/635256384442859530.gif?size=32)

**Comment by mh-test** [comment]
@michal-hudy ![blob](https://cdn.discordapp.com/emojis/468995798512959508.gif?size=32)

**Comment by mh-test** [comment]
@bszwarc ![blob](https://cdn.discordapp.com/emojis/635256314070695977.gif?size=32)

**Comment by mh-test** [comment]
@bszwarc ![blob](https://cdn.discordapp.com/emojis/635255958930456581.gif?size=32)

**Comment by mh-test** [comment]
@michal-hudy ![blob](https://cdn.discordapp.com/emojis/635256314070695977.gif?size=16)

**Comment by mh-test** [comment]
@michal-hudy ![blob](https://cdn.discordapp.com/emojis/635256397621231636.gif?size=32)

**Comment by mh-test** [comment]
@bszwarc ![blob](https://cdn.discordapp.com/emojis/635256384442859530.gif?size=32)

**Comment by mh-test** [comment]
@bszwarc ![blob](https://cdn.discordapp.com/emojis/492776678742032395.gif?size=32)

**Comment by mh-test** [comment]
@bszwarc ![blob](https://cdn.discordapp.com/emojis/414286078346788864.gif?size=32)
